"""Classification plan: the operator's persisted, auditable decision record.

A plan is a TOML file. ``--dry-run`` writes an annotated plan; a real run reads
it. The persisted, authoritative parts are ``[scope]`` (objects to extract),
``[overrides.<Object>]`` (field → action), and ``[reasons.<Object>]`` (required
justification when keeping a special-category field). Recommendations are NOT
trusted from the file — the tool re-derives them every run, so a field added to
the org after the plan was written is reclassified by the conservative default
(drift-safe).
"""
from __future__ import annotations

import tomllib
from dataclasses import dataclass
from pathlib import Path

from sf_clean_room.constants import DROP, KEEP, OVERRIDE_ACTIONS, PASS
from sf_clean_room.schema_scan import ScannedField


class PlanError(RuntimeError):
    pass


@dataclass(frozen=True)
class Plan:
    objects: list[str]
    overrides: dict[str, dict[str, str]]  # object -> {field: action}
    reasons: dict[str, dict[str, str]]    # object -> {field: justification}
    known_fields: dict[str, set[str]]     # object -> {field, ...} from when authored

    def override_for(self, obj: str, field: str) -> str | None:
        return self.overrides.get(obj, {}).get(field)

    def reason_for(self, obj: str, field: str) -> str:
        return self.reasons.get(obj, {}).get(field, "")

    def is_known(self, obj: str, field: str) -> bool:
        return field in self.known_fields.get(obj, set())


@dataclass(frozen=True)
class Effective:
    action: str
    reason: str
    source: str            # "default" | "override"
    special_category: bool
    downgraded: bool       # special-category keep without a justification → DROP


def load_plan(path: Path) -> Plan:
    try:
        with open(path, "rb") as f:
            data = tomllib.load(f)
    except tomllib.TOMLDecodeError as e:
        raise PlanError(f"plan file is not valid TOML: {path}: {e}") from e

    objects = list(data.get("scope", {}).get("objects", []))

    def _str_map(section: dict) -> dict[str, dict[str, str]]:
        out: dict[str, dict[str, str]] = {}
        for obj, fields in (section or {}).items():
            if isinstance(fields, dict):
                out[obj] = {str(k): str(v) for k, v in fields.items()}
        return out

    overrides = _str_map(data.get("overrides", {}))
    for obj, fields in overrides.items():
        for field, action in fields.items():
            if action not in OVERRIDE_ACTIONS:
                raise PlanError(
                    f"plan override {obj}.{field} = {action!r} is not a valid action "
                    f"(one of {sorted(OVERRIDE_ACTIONS)})"
                )

    reasons = _str_map(data.get("reasons", {}))
    known_raw = data.get("known_fields", {}) or {}
    known: dict[str, set[str]] = {
        obj: {str(x) for x in names} for obj, names in known_raw.items() if isinstance(names, list)
    }
    return Plan(objects=objects, overrides=overrides, reasons=reasons, known_fields=known)


def resolve(obj: str, sf: ScannedField, plan: Plan | None) -> Effective:
    """Resolve the effective action for a scanned field under an optional plan."""
    rec = sf.recommendation
    if plan is None:
        return Effective(rec.action, rec.reason, "default", rec.special_category, False)

    ov = plan.override_for(obj, sf.meta.name)
    if ov is None:
        return Effective(rec.action, rec.reason, "default", rec.special_category, False)

    action = PASS if ov == KEEP else ov

    # Keeping/exposing a special-category field requires a recorded justification.
    if rec.special_category and action != DROP:
        reason_txt = plan.reason_for(obj, sf.meta.name)
        if not reason_txt:
            return Effective(
                DROP,
                f"special-category override '{action}' lacks required justification "
                f"in [reasons.{obj}] -> downgraded to DROP",
                "override",
                True,
                True,
            )
        return Effective(action, f"operator override {action} (justified: {reason_txt})", "override", True, False)

    return Effective(action, f"operator override {action}", "override", rec.special_category, False)


def emit_plan(scan: dict[str, list[ScannedField]]) -> str:
    """Render an annotated, editable plan from a scan."""
    objects = list(scan.keys())
    lines: list[str] = [
        "# sf-clean-room get_records - classification plan",
        "# Generated by --dry-run. Edit [overrides.*] / [reasons.*], then run without --dry-run.",
        "# Override actions: DROP, HASH_EMAIL, HASH_ID, RAW, PASS, KEEP (=keep raw), DERIVE.",
        "# Keeping a special-category field requires a justification in [reasons.<Object>],",
        "# otherwise that field is downgraded to DROP at extract time.",
        "",
        "[scope]",
        "objects = [" + ", ".join(f'"{o}"' for o in objects) + "]",
        "",
    ]
    for obj, fields in scan.items():
        lines.append(f"# ---- {obj} ----")
        lines.append("# Recommended (informational; re-derived each run):")
        for sf in fields:
            r = sf.recommendation
            tag = " [SPECIAL-CATEGORY]" if r.special_category else ""
            lines.append(f"#   {sf.meta.name:<40} {r.action:<11} {r.reason}{tag}")
        lines.append(f"[overrides.{obj}]")
        lines.append("")
        lines.append(f"[reasons.{obj}]")
        lines.append("")

    lines.append("[known_fields]")
    for obj, fields in scan.items():
        names = ", ".join(f'"{sf.meta.name}"' for sf in fields)
        lines.append(f"{obj} = [{names}]")
    lines.append("")
    return "\n".join(lines)
